### ISSUE TITLE
allSoftware is not defined

### ISSUE THREAD

**Issue by Rsl1122** [Bastian/bStats#129]
Hi, I got this error on https://bstats.org/plugin/bungeecord/Plan, it worked fine a few hours before so I think todays commits broke it

```
ReferenceError: /home/bastian/bStats/views/error.ejs:17
    15| <body>

    16| 

 >> 17| <% include templates/navigation.ejs %>

    18| <main>

    19|     <div class="container">

    20|         <% if (message == 'Not Found') { %>


/home/bastian/bStats/views/templates/navigation.ejs:35
    33|         </li>

    34|         <li><a class="subheader"><i class="material-icons left" style="font-size: 30px">language</i>Global stats</a></li>

 >> 35|         <% for (var i = 0; i < allSoftware.length; i++) { %>

    36|         <% if (allSoftware[i].globalPlugin) { %>

    37|         <li><a href="/global/<%= allSoftware[i].url %>"><%= allSoftware[i].name %></a></li>

    38|         <% } %>


allSoftware is not defined
    at eval (eval at compile (/home/bastian/bStats/node_modules/ejs/lib/ejs.js:592:12), <anonymous>:43:28)
    at eval (eval at compile (/home/bastian/bStats/node_modules/ejs/lib/ejs.js:592:12), <anonymous>:173:10)
    at returnedFn (/home/bastian/bStats/node_modules/ejs/lib/ejs.js:623:17)
    at tryHandleCache (/home/bastian/bStats/node_modules/ejs/lib/ejs.js:251:36)
    at View.exports.renderFile [as engine] (/home/bastian/bStats/node_modules/ejs/lib/ejs.js:480:10)
    at View.render (/home/bastian/bStats/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/bastian/bStats/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/bastian/bStats/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/bastian/bStats/node_modules/express/lib/response.js:1008:7)
    at /home/bastian/bStats/app.js:157:9
    at Layer.handle_error (/home/bastian/bStats/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/bastian/bStats/node_modules/express/lib/router/index.js:315:13)
    at /home/bastian/bStats/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/bastian/bStats/node_modules/express/lib/router/index.js:335:12)
    at next (/home/bastian/bStats/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/home/bastian/bStats/node_modules/express/lib/router/layer.js:67:12)
```

**Comment by Bastian** [comment]
Fixed, thanks for reporting 👍
