### ISSUE TITLE
Servers running NanaicaMC dont show but my server is running it

### ISSUE THREAD

**Issue by PancakseYT** [Bastian/bStats#167]
![image](https://github.com/Bastian/bStats/assets/84547061/bcd1693f-3f89-4fd9-954e-3c76a8c2a26d)
![image](https://github.com/Bastian/bStats/assets/84547061/75ddc3ff-793c-4496-b705-9870b9223e79)
 How am i gonna fix it?

**Comment by PancakseYT** [comment]
heres the link to my bstats https://bstats.org/plugin/server-implementation/NanaicaMC/19838

**Comment by Dueris** [comment]
Show paper metrics file. Specifically the showMetrics method if I remember correctly

**Comment by PancakseYT** [comment]
how do i fix

**Comment by MiniDigger** [comment]
attach.
a.
debugger.

**Comment by PancakseYT** [comment]
where

**Comment by MiniDigger** [comment]
to bstats to see what its sending and what its getting back

**Comment by Dueris** [comment]
Ensure you have a similar patch to this:
https://github.com/Dueris/CanvasMC/commit/6c8aa256f6be56d66c7c544a519172dfc6a68db4

If you don't thats probably ur issue

**Comment by PancakseYT** [comment]
@Dueris i added it still not working

**Comment by PancakseYT** [comment]
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1)
OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (build 18.0.2.1+1, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -Xmx4096M -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
Applying patches
Starting org.bukkit.craftbukkit.Main
System Info: Java 18 (OpenJDK 64-Bit Server VM 18.0.2.1+1) Host: Linux 5.4.0-150-generic (amd64)
Loading libraries, please wait...
[23:37:02 INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[23:37:03 INFO]: Loaded 7 recipes
[23:37:04 INFO]: Starting minecraft server version 1.20.2
[23:37:04 INFO]: Loading properties
[23:37:04 INFO]: This server is running Nanaica version git-Nanaica-"11b1b24" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 11b1b24 on ver/1.20.2)
[23:37:05 INFO]: Server Ping Player Sample Count: 12
[23:37:05 INFO]: Using 4 threads for Netty based IO
[23:37:05 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[23:37:06 WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[23:37:06 WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[23:37:06 WARN]: [Pufferfish] If you have already added this flag, then SIMD operations are not supported on your JVM or CPU.
[23:37:06 WARN]: [Pufferfish] Debug: Java: 18.0.2.1, test run: true
[23:37:06 INFO]: Default game type: SURVIVAL
[23:37:06 INFO]: Generating keypair
[23:37:06 INFO]: Starting Minecraft server on 0.0.0.0:4027
[23:37:06 INFO]: Using epoll channel type
[23:37:06 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[23:37:06 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[23:37:06 ERROR]: [ModernPluginLoadingStrategy] Ambiguous plugin name 'ViaBackwards' for files 'plugins/viabackwards.jar' and 'plugins/ViaBackwards-4.8.1.jar' in 'plugins'
[23:37:07 INFO]: [SpigotLibraryLoader] [VotingPlugin] Loading 1 libraries... please wait
[23:37:07 INFO]: [SpigotLibraryLoader] [VotingPlugin] Loaded library /home/container/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
[23:37:07 INFO]: [SpigotLibraryLoader] [VotingPlugin] Loaded library /home/container/libraries/org/ow2/asm/asm/7.3.1/asm-7.3.1.jar
[23:37:07 INFO]: [SpigotLibraryLoader] [VotingPlugin] Loaded library /home/container/libraries/org/ow2/asm/asm-commons/7.3.1/asm-commons-7.3.1.jar
[23:37:07 INFO]: [SpigotLibraryLoader] [VotingPlugin] Loaded library /home/container/libraries/org/ow2/asm/asm-analysis/7.3.1/asm-analysis-7.3.1.jar
[23:37:07 INFO]: [SpigotLibraryLoader] [VotingPlugin] Loaded library /home/container/libraries/org/ow2/asm/asm-tree/7.3.1/asm-tree-7.3.1.jar
[23:37:07 INFO]: [SpigotLibraryLoader] [VotingPlugin] Loaded library /home/container/libraries/org/ow2/asm/asm-util/7.3.1/asm-util-7.3.1.jar
[23:37:07 WARN]: [org.bukkit.craftbukkit.v1_20_R2.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[23:37:11 WARN]: Legacy plugin SimpleTpa v6.4 does not specify an api-version.
[23:37:11 INFO]: [ViaVersion] Loading server plugin ViaVersion v4.8.1
[23:37:11 INFO]: [ViaVersion] ViaVersion 4.8.1 is now loaded. Registering protocol transformers and injecting...
[23:37:12 INFO]: [ViaVersion] Loading block connection mappings ...
[23:37:12 INFO]: [ViaBackwards] Loading translations...
[23:37:12 INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[23:37:12 INFO]: [ViaBackwards] Registering protocols...
[23:37:13 INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.102
[23:37:13 INFO]: [Vault] Loading server plugin Vault v1.7.3-b131
[23:37:13 INFO]: [Essentials] Loading server plugin Essentials v2.21.0-dev+18-fdf1875
[23:37:13 INFO]: [TheGoldEconomy] Loading server plugin TheGoldEconomy v1.5.2
[23:37:13 INFO]: [CoreProtect] Loading server plugin CoreProtect v22.2
[23:37:13 INFO]: [floodgate] Loading server plugin floodgate v2.2.2-SNAPSHOT (b85-71acc6c)
[23:37:14 INFO]: [floodgate] Took 499ms to boot Floodgate
[23:37:14 INFO]: [SuperVanish] Loading server plugin SuperVanish v6.2.18
[23:37:14 INFO]: [Towny] Loading server plugin Towny v0.100.0.0
[23:37:14 INFO]: [spark] Loading server plugin spark v1.10.55
[23:37:14 INFO]: [Geyser-Spigot] Loading server plugin Geyser-Spigot v2.2.0-SNAPSHOT
[23:37:14 INFO]: [Geyser-Spigot] Loading extensions...
[23:37:14 INFO]: [Geyser-Spigot] Loaded 0 extension(s)
[23:37:14 INFO]: [GSit] Loading server plugin GSit v1.5.0
[23:37:14 INFO]: [VotingPlugin] Loading server plugin VotingPlugin v6.14.1
[23:37:14 INFO]: [TownyChat] Loading server plugin TownyChat v0.109
[23:37:14 INFO]: [PurpurExtras] Loading server plugin PurpurExtras v1.28.0
[23:37:14 INFO]: [SimpleTpa] Loading server plugin SimpleTpa v6.4
[23:37:14 INFO]: [Maintenance] Loading server plugin Maintenance v4.2.0
[23:37:14 INFO]: [ViaBackwards] Loading server plugin ViaBackwards v4.8.1
[23:37:14 INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:37:14 INFO]: [LuckPerms] Enabling LuckPerms v5.4.102
[23:37:15 INFO]:         __    
[23:37:15 INFO]:   |    |__)   LuckPerms v5.4.102
[23:37:15 INFO]:   |___ |      Running on Bukkit - Nanaica
[23:37:15 INFO]: 
[23:37:15 INFO]: [LuckPerms] Loading configuration...
[23:37:15 INFO]: [LuckPerms] Loading storage provider... [H2]
[23:37:16 INFO]: [LuckPerms] Loading internal permission managers...
[23:37:16 INFO]: [LuckPerms] Performing initial data load...
[23:37:16 INFO]: [LuckPerms] Successfully enabled. (took 1863ms)
[23:37:16 INFO]: [Vault] Enabling Vault v1.7.3-b131
[23:37:16 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[23:37:16 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[23:37:16 INFO]: [Vault] Enabled Version 1.7.3-b131
[23:37:16 INFO]: [LuckPerms] Registered Vault permission & chat hook.
[23:37:16 INFO]: [TheGoldEconomy] Enabling TheGoldEconomy v1.5.2
[23:37:16 INFO]: [TheGoldEconomy] §aVaultAPI hooked into §bTheGoldEconomy
[23:37:17 INFO]: Preparing level "world"
[23:37:17 INFO]: -------- World Settings For [world] --------
[23:37:18 INFO]: -------- World Settings For [world_nether] --------
[23:37:18 INFO]: -------- World Settings For [world_the_end] --------
[23:37:18 INFO]: Preparing start region for dimension minecraft:overworld
[23:37:19 INFO]: Time elapsed: 659 ms
[23:37:19 INFO]: Preparing start region for dimension minecraft:the_nether
[23:37:19 INFO]: Time elapsed: 126 ms
[23:37:19 INFO]: Preparing start region for dimension minecraft:the_end
[23:37:19 INFO]: Time elapsed: 91 ms
[23:37:19 INFO]: [ViaVersion] Enabling ViaVersion v4.8.1
[23:37:19 INFO]: [ViaVersion] ViaVersion detected server version: 1.20.2 (764)
[23:37:19 INFO]: [Essentials] Enabling Essentials v2.21.0-dev+18-fdf1875
[23:37:20 INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[23:37:20 INFO]: [Essentials] No kits found to migrate.
[23:37:20 INFO]: [Essentials] Loaded 39094 items from items.json.
[23:37:20 INFO]: [Essentials] Using locale en_US
[23:37:21 INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[23:37:21 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[23:37:21 INFO]: [Vault] [Economy] Essentials Economy hooked.
[23:37:21 INFO]: [Essentials] Using Vault based permissions (LuckPerms)
[23:37:21 INFO]: [CoreProtect] Enabling CoreProtect v22.2
[23:37:21 INFO]: [CoreProtect] CoreProtect has been successfully enabled! 
[23:37:21 INFO]: [CoreProtect] Using SQLite for data storage.
[23:37:21 INFO]: --------------------
[23:37:21 INFO]: [CoreProtect] Enjoy CoreProtect? Join our Discord!
[23:37:21 INFO]: [CoreProtect] Discord: www.coreprotect.net/discord/
[23:37:21 INFO]: --------------------
[23:37:21 INFO]: [floodgate] Enabling floodgate v2.2.2-SNAPSHOT (b85-71acc6c)
[23:37:22 INFO]: [SuperVanish] Enabling SuperVanish v6.2.18
[23:37:22 INFO]: [SuperVanish] Please install ProtocolLib to be able to use all SuperVanish features: https://www.spigotmc.org/resources/protocollib.1997/
[23:37:22 INFO]: [SuperVanish] Hooked into Essentials
[23:37:22 INFO]: [Towny] Enabling Towny v0.100.0.0
[23:37:22 INFO]: ====================      Towny      ========================
[23:37:24 INFO]: [Towny] Successfully loaded translations for 42 languages.
[23:37:25 INFO]: [Towny] Config: Loaded 9 townblock types: shop, inn, arena, jail, default, bank, wilds, farm, embassy.
[23:37:25 INFO]: [Towny] Database: [Load] flatfile [Save] flatfile
[23:37:25 INFO]: [Towny] Database: Loaded in 90ms.
[23:37:25 INFO]: [Towny] Database: 100% of residents have stored UUIDs.
[23:37:25 INFO]: [Towny] Cleaning up old backups...
[23:37:25 INFO]: [Towny] Successfully cleaned backups.
[23:37:25 INFO]: [Towny] Making backup...
[23:37:25 INFO]: [Towny] Time until a New Day: 12 hours, 22 minutes, 35 seconds
[23:37:25 INFO]: [Towny] Checking for updates...
[23:37:25 INFO]: [Towny] Searching for third-party plugins...
[23:37:25 INFO]: [Towny] Plugins found: 
[23:37:25 INFO]: [Towny]   Permissions: TownyPerms, LuckPerms v5.4.102 via Vault
[23:37:25 INFO]: [Towny]   Chat: LuckPerms v5.4.102 via Vault
[23:37:25 INFO]: [Towny]   Economy: TheGoldEconomy via Vault
[23:37:25 INFO]: [Towny]   Add-ons: TownyChat v0.109
[23:37:26 INFO]: =============================================================
[23:37:26 INFO]: [Towny] Version: 0.100.0.0 - Plugin Enabled
[23:37:26 INFO]: =============================================================
[23:37:26 INFO]: [spark] Enabling spark v1.10.55
[23:37:26 INFO]: [Towny] New update available: 0.100.0.1 | Current version: 0.100.0.0
[23:37:26 INFO]: [Towny] Download it here: https://github.com/TownyAdvanced/Towny/releases/tag/0.100.0.1
[23:37:26 INFO]: [Towny] Towny flatfiles and settings successfully backed up.
[23:37:26 INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[23:37:26 INFO]: [spark] Starting background profiler...
[23:37:27 WARN]: [floodgate] 
**********************************
* The prefix you entered in your Floodgate config (_) could lead to username conflicts!
* Should a Java player join with the username _Notch, and a Bedrock player join as Notch (who will be given the name _Notch), unwanted results will happen!
* We strongly recommend using . as the prefix, but other alternatives that will not conflict include: +, - and *
**********************************
[23:37:27 INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.2.0-SNAPSHOT
[23:37:27 INFO]: [GSit] Enabling GSit v1.5.0
[23:37:27 INFO]: [GSit] The plugin was successfully enabled.
[23:37:27 INFO]: [GSit] New version available: 1.5.3!
[GSit] Current version: 1.5.0!
[GSit] Download the latest version:
[GSit] https://www.spigotmc.org/resources/62325
[23:37:27 INFO]: [VotingPlugin] Enabling VotingPlugin v6.14.1
[23:37:27 WARN]: [VotingPlugin] Detected no voting sites, this may mean something isn't properly setup
[23:37:27 INFO]: [VotingPlugin] Loaded LuckPerms hook!
[23:37:28 INFO]: [VotingPlugin] Giving VotingPlugin.Player permission by default, can be disabled in the config
[23:37:28 WARN]: [VotingPlugin] No VotifierEvent found, install Votifier, NuVotifier, or another Votifier plugin
[23:37:28 INFO]: [VotingPlugin] Enabled VotingPlugin 6.14.1
[23:37:28 INFO]: [TownyChat] Enabling TownyChat v0.109
[23:37:28 INFO]: [TownyChat] Towny version 0.100.0.0 found.
[23:37:28 INFO]: [TownyChat] Default Channel set to general
[23:37:28 INFO]: [PurpurExtras] Enabling PurpurExtras v1.28.0
[23:37:28 INFO]: [org.purpurmc.purpurextras.reflections.Reflections] Reflections took 86 ms to scan 1 urls, producing 3 keys and 63 values
[23:37:29 INFO]: [SimpleTpa] Enabling SimpleTpa v6.4*
[23:37:29 INFO]: [SimpleTpa] If you need support contact me at https://discord.gg/SZUkza9
[23:37:29 INFO]: [SimpleTpa] Simple Tpa has been enabled on version 6.4
[23:37:29 INFO]: Enabled metrics. You may opt-out by changing plugins/bStats/config.yml
[23:37:29 INFO]: [Maintenance] Enabling Maintenance v4.2.0
[23:37:29 INFO]: [ViaBackwards] Enabling ViaBackwards v4.8.1
[23:37:29 INFO]: [Geyser-Spigot] ******************************************
[23:37:29 INFO]: [Geyser-Spigot] 
[23:37:29 INFO]: [Geyser-Spigot] Loading Geyser version 2.2.0-SNAPSHOT (git-master-8d2ebcf)
[23:37:29 INFO]: [Geyser-Spigot] 
[23:37:29 INFO]: [Geyser-Spigot] ******************************************
[23:37:36 INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:19132
[23:37:36 INFO]: [Geyser-Spigot] Done (6.602s)! Run /geyser help for help!
[23:37:36 INFO]: Running delayed init tasks
[23:37:36 INFO]: [Essentials] Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
[23:37:36 INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[23:37:36 INFO]: [Essentials] Fetching version information...
[23:37:36 INFO]: [TownyChat] -******* TownyChat enabled *******-
[23:37:36 INFO]: Done (32.208s)! For help, type "help"
container@pterodactyl~ Server marked as running...
[23:37:36 INFO]: [Vault] Checking for Updates ... 
[23:37:36 WARN]: [Essentials] You're 1 EssentialsX dev build(s) out of date!
[23:37:36 WARN]: [Essentials] Download it here: https://essentialsx.net/downloads.html
[23:37:36 INFO]: [Vault] No new version available
[23:37:36 INFO]: [TheGoldEconomy] &fYou are using an outdated version of the plugin. Please update to the latest version.
[23:37:41 INFO]: [VotingPlugin] Successfully hooked into vault economy!
[23:37:41 INFO]: [VotingPlugin] Hooked into vault permissions
[23:37:46 INFO]: [VotingPlugin] VotingPlugin is up to date! Version: 6.14.1
[23:40:55 WARN]: [Essentials] Failed to get data for custom chart with id permsPlugin
java.lang.IllegalArgumentException: class me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission is not provided by a interface io.papermc.paper.plugin.provider.classloader.ConfiguredPluginClassLoader
        at org.bukkit.plugin.java.JavaPlugin.getProvidingPlugin(JavaPlugin.java:451) ~[nanaica-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getBackendName(AbstractVaultHandler.java:104) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at com.earth2me.essentials.perm.PermissionsHandler.getBackendName(PermissionsHandler.java:148) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at com.earth2me.essentials.metrics.MetricsWrapper.lambda$addPermsChart$0(MetricsWrapper.java:55) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at com.earth2me.essentials.libs.bstats.charts.DrilldownPie.getChartData(DrilldownPie.java:27) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at com.earth2me.essentials.libs.bstats.charts.CustomChart.getRequestJsonObject(CustomChart.java:22) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at com.earth2me.essentials.libs.bstats.MetricsBase.lambda$submitData$2(MetricsBase.java:146) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at com.earth2me.essentials.libs.bstats.MetricsBase.submitData(MetricsBase.java:148) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[nanaica-1.20.2.jar:git-Nanaica-"11b1b24"]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[nanaica-1.20.2.jar:git-Nanaica-"11b1b24"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1497) ~[nanaica-1.20.2.jar:git-Nanaica-"11b1b24"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:495) ~[nanaica-1.20.2.jar:git-Nanaica-"11b1b24"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[nanaica-1.20.2.jar:git-Nanaica-"11b1b24"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[nanaica-1.20.2.jar:git-Nanaica-"11b1b24"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[nanaica-1.20.2.jar:git-Nanaica-"11b1b24"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:45:04 WARN]: [Essentials] Failed to get data for custom chart with id permsPlugin
java.lang.IllegalArgumentException: class me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission is not provided by a interface io.papermc.paper.plugin.provider.classloader.ConfiguredPluginClassLoader
        at org.bukkit.plugin.java.JavaPlugin.getProvidingPlugin(JavaPlugin.java:451) ~[nanaica-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getBackendName(AbstractVaultHandler.java:104) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at com.earth2me.essentials.perm.PermissionsHandler.getBackendName(PermissionsHandler.java:148) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at com.earth2me.essentials.metrics.MetricsWrapper.lambda$addPermsChart$0(MetricsWrapper.java:55) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at com.earth2me.essentials.libs.bstats.charts.DrilldownPie.getChartData(DrilldownPie.java:27) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at com.earth2me.essentials.libs.bstats.charts.CustomChart.getRequestJsonObject(CustomChart.java:22) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at com.earth2me.essentials.libs.bstats.MetricsBase.lambda$submitData$2(MetricsBase.java:146) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at com.earth2me.essentials.libs.bstats.MetricsBase.submitData(MetricsBase.java:148) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[nanaica-1.20.2.jar:git-Nanaica-"11b1b24"]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[nanaica-1.20.2.jar:git-Nanaica-"11b1b24"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1497) ~[nanaica-1.20.2.jar:git-Nanaica-"11b1b24"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:495) ~[nanaica-1.20.2.jar:git-Nanaica-"11b1b24"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[nanaica-1.20.2.jar:git-Nanaica-"11b1b24"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[nanaica-1.20.2.jar:git-Nanaica-"11b1b24"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[nanaica-1.20.2.jar:git-Nanaica-"11b1b24"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:45:05 WARN]: [Essentials] Could not submit bStats metrics data
java.io.IOException: Server returned HTTP response code: 429 for URL: https://bStats.org/api/v2/data/bukkit
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at com.earth2me.essentials.libs.bstats.MetricsBase.sendData(MetricsBase.java:196) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at com.earth2me.essentials.libs.bstats.MetricsBase.lambda$submitData$4(MetricsBase.java:161) ~[EssentialsX-2.21.0-dev+18-fdf1875.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

those my  logs
